branches:
  only:
    - master

if: tag IS present

cache:
  bundler: true
  cocoapods: true
  directories:
    - $HOME/.android/build-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.pub-cache

before_install:
  - cd $PLATFORM
  - bundle update
install:
  - bundle install
  - cd ..
  - git clone https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:$PATH
before_script:
  - flutter config --no-analytics
  - flutter channel beta
  - flutter doctor --verbose
  - flutter test
script:
  - flutter packages get
  - cd $PLATFORM
  - bundle exec fastlane release

matrix:
  include:
    # Android
    - language: android
      env:
        - PLATFORM=android

    # iOS
    - language: swift
      os: osx
      osx_image: xcode9.4
      env:
        - PLATFORM=ios
