branches:
  only:
    - master

language: swift
os: osx
osx_image: xcode9.4

cache:
  directories:
    - $HOME/.pub-cache

before_install:
  - brew update
  - brew upgrade
install:
  - brew install fastlane
  - fastlane update_fastlane
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  - export PATH=`pwd`/flutter/bin:$PATH

before_script:
  - flutter doctor --verbose
  - flutter config --no-analytics
  - flutter test
script:
  - flutter packages get
  - fastlane release
