name: pikapp
description: Pikatea\'s app!
version: 0.2.5+25

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  after_layout: ^1.0.4
  # async: ^2.0.7
  cached_network_image: ^0.4.1
  cloud_firestore: ^0.7.4
  cloud_functions: ^0.0.2
  device_info: ^0.2.1
  firebase_analytics: ^1.0.3
  firebase_messaging: ^1.0.5
  firebase_remote_config: ^0.0.5
  flutter_staggered_grid_view: ^0.2.2
  # flutter_youtube: ^0.1.2
  font_awesome_flutter: ^8.0.1
  package_info: ^0.3.2
  sentry: ^2.1.0
  share: ^0.5.3
  shared_preferences: ^0.4.2
  url_launcher: ^3.0.3

dependency_overrides:
  uuid: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: "^2.0.0"
  flutter: "^0.6.0"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/resources/assets/home_1.jpg
    - lib/resources/assets/home_2.jpg
    - lib/resources/assets/icon.png
  fonts:
    - family: Courgette
      fonts:
        - asset: lib/resources/fonts/Courgette-Regular.ttf
    - family: Nunito
      fonts:
        - asset: lib/resources/fonts/Nunito-Black.ttf
          weight: 900
        - asset: lib/resources/fonts/Nunito-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: lib/resources/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: lib/resources/fonts/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: lib/resources/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: lib/resources/fonts/Nunito-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: lib/resources/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: lib/resources/fonts/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: lib/resources/fonts/Nunito-Italic.ttf
          style: italic
        - asset: lib/resources/fonts/Nunito-Light.ttf
          weight: 300
        - asset: lib/resources/fonts/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: lib/resources/fonts/Nunito-Regular.ttf
        - asset: lib/resources/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: lib/resources/fonts/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
