username("lorenzo196pieri@gmail.com") # Your Apple email address
app_identifier("yt.pikatea.app") # The bundle identifier of your app

skip_metadata(true)
skip_screenshots(true)

force(true) # Skip the HTML report file verification
copyright("#{Time.now.year} Lorenzo Pieri")

submit_for_review(true)
automatic_release(true)
