opt_out_usage
setup_travis

default_platform(:ios)

platform :ios do

  desc "Push a new release build to the App Store"
  lane :release do
    build
    cert
    sigh
    gym
    deliver
  end


  desc "Analyze the Flutter app"
  lane :build do
    # ensure_git_status_clean(show_uncommitted_changes: true)

    Dir.chdir("../../") do
      sh("flutter", "analyze")
      sh("flutter", "build", "ios", "--no-codesign")
    end
  end

end
