default_platform(:ios)

platform :ios do

  desc "Push a new release build to the App Store"
  lane :release do
    analyze
    cert
    sigh
    gym
    deliver
  end


  desc "Analyze the Flutter app"
  lane :analyze do
    # ensure_git_status_clean(show_uncommitted_changes: true)

    Dir.chdir("../../") do
      sh("flutter", "analyze")
    end
  end

end
