ENV["SUPPLY_APK"] = "../build/app/outputs/apk/release/app-release.apk"
ENV["SUPPLY_JSON_KEY"] = "/Users/lrnz09/Development/Google_Play_Android_Developer-e96c8acff6e0.json"

opt_out_usage
setup_travis

default_platform(:android)

platform :android do

  desc "Push a new beta build to the Play Store"
  lane :beta do
    build
    upload(beta: true)
  end

  desc "Push a new release build to the Play Store"
  lane :release do
    build
    upload
  end

  desc "Build a new version of the app"
  lane :build do
    # ensure_git_status_clean(show_uncommitted_changes: true)

    Dir.chdir("../../") do
      sh("flutter", "analyze")
      sh("flutter", "build", "apk")
    end
  end

  desc "Upload a new build to the Google Play"
  lane :upload do |options|
    if options[:beta]
      supply(track: 'beta')
    else
      supply
    end
  end

end
